# file: ansible-role-irony/tasks/install.yml

- name: IRONY | get from git repository
  become: true
  git: repo="{{ irony_repo_url }}"
       dest="{{ irony_tmp }}"
       version="{{ irony_version }}"
  register: irony_downloaded

- name: IRONY | Create build directory
  become: true
  file:
    path: "{{ irony_build_dir }}"
    state: directory

- name: IRONY | run cmake
  become: true
  command: chdir="{{ irony_build_dir }}" cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
           -DCMAKE_C_COMPILER={{llvm_install_dir}}/bin/clang \
           -DCMAKE_CXX_COMPILER={{llvm_install_dir}}/bin/clang++ \
           -DLIBCLANG_LIBRARY={{llvm_install_dir}}/lib/libclang.so \
           -DLIBCLANG_INCLUDE_DIR={{llvm_install_dir}}/include \
           -DCLANG_RESOURCE_DIR={{llvm_install_dir}}/lib/clang/4.0.1 \
           -DCMAKE_INSTALL_PREFIX={{irony_install_dir}} \
           -DCMAKE_CXX_LINK_FLAGS="-L{{gcc_install_dir}}/lib64 -Wl,-rpath,{{gcc_install_dir}}/lib64" \
           -DCMAKE_INSTALL_RPATH="{{gcc_install_dir}}/lib64" \
           -DCMAKE_INSTALL_RPATH={{llvm_install_dir}}/lib \
           -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE \
           -DCMAKE_BUILD_TYPE=Release \
           "{{ irony_tmp }}/server"
  when: irony_downloaded.changed

- name: IRONY | create install path
  become: true
  file:
    path: "{{irony_install_dir}}/share/emacs/site-lisp/"
    state: directory
  when: irony_downloaded.changed

- name: IRONY | make
  become: true
  command: chdir="{{ irony_build_dir }}" make
  when: irony_downloaded.changed

- name: IRONY | make install
  become: true
  command: chdir="{{ irony_build_dir }}" make install
  when: irony_downloaded.changed

- name: IRONY | get lisp that needs to be installed
  shell: find {{ irony_tmp }} -name ".el" -prune -o -print
  register: irony_lisp_names
  when: irony_downloaded.changed

- name: IRONY | install lisp files
  command: cp {{ item }} "{{irony_install_dir}}/share/emacs/site-lisp/"
  with_items: "{{ irony_lisp_names.stdout_lines }}"
  when: irony_list.changed
